#!/usr/bin/env php
<?php

define('APP_CLI', true);

require __DIR__.'/bootstrap.php';

use Symfony\Component\Console\Application;

$app = Cockpit::instance();
$cli = new Application("Tower - {$app['app.name']}", $app['app.version']);

$app->trigger('cli.bootstrap', [$cli]);

$cli->run();